
import pandas as pd
from utils import *


# ResultTable overview - Sales_demographic 

# SALES_DEMOGRAPHIC_DEMOGRAPHIC_CODE
# SALES_DEMOGRAPHIC_SALES_PERCENT
# RETAILER_HEADQUARTERS_RETAILER_CODEMR
# RETAILER_HEADQUARTERS_RETAILER_NAME
# RETAILER_HEADQUARTERS_ADDRESS1
# RETAILER_HEADQUARTERS_ADDRESS2
# RETAILER_HEADQUARTERS_CITY
# RETAILER_HEADQUARTERS_REGION
# RETAILER_HEADQUARTERS_POSTAL_ZONE
# RETAILER_HEADQUARTERS_PHONE
# RETAILER_HEADQUARTERS_FAX
# RETAILER_SEGMENT_SEGMENT_CODE
# RETAILER_SEGMENT_LANGUAGE
# RETAILER_SEGMENT_SEGMENT_NAME
# RETAILER_SEGMENT_SEGMENT_DESCRIPTION
# AGE_GROUP_AGE_GROUP_CODE
# AGE_GROUP_UPPER_AGE
# AGE_GROUP_LOWER_AGE
# RETAILER_COUNTRY_COUNTRY_CODE
# RETAILER_COUNTRY_COUNTRY_EN
# RETAILER_COUNTRY_FLAG_IMAGE
# SALES_TERRITORY_SALES_TERRITORY_CODE
# SALES_TERRITORY_TERRITORY_NAME_EN


go_crm = load_db('source/go_crm.sqlite')


retailer_heaquarters = load_table(go_crm, 'retailer_headquarters').add_prefix('RETAILER_HEADQUARTERS_')
retailer_site = load_table(go_crm, 'retailer_site').add_prefix('RETAILER_SITE_')
retailer_segment = load_table(go_crm, 'retailer_segment').add_prefix('RETAILER_SEGMENT_')
retailer_country = load_table(go_crm, 'country').add_prefix('RETAILER_COUNTRY_')
sales_demographic = load_table(go_crm, 'sales_demographic').add_prefix('SALES_DEMOGRAPHIC_')
sales_territory = load_table(go_crm, 'sales_territory').add_prefix('SALES_TERRITORY_')
age_group = load_table(go_crm, 'age_group').add_prefix('AGE_GROUP_')


result = pd.merge(
    sales_demographic, retailer_heaquarters, left_on="SALES_DEMOGRAPHIC_RETAILER_CODEMR", right_on="RETAILER_HEADQUARTERS_RETAILER_CODEMR"
    ).drop(columns='SALES_DEMOGRAPHIC_RETAILER_CODEMR')

result = pd.merge(
    result, retailer_segment, left_on='RETAILER_HEADQUARTERS_SEGMENT_CODE', right_on='RETAILER_SEGMENT_SEGMENT_CODE'
    ).drop(columns='RETAILER_HEADQUARTERS_SEGMENT_CODE')

result = pd.merge(
    result, age_group, left_on="SALES_DEMOGRAPHIC_AGE_GROUP_CODE", right_on="AGE_GROUP_AGE_GROUP_CODE"
    ).drop(columns='SALES_DEMOGRAPHIC_AGE_GROUP_CODE')

result = pd.merge(
    result, retailer_country, left_on='RETAILER_HEADQUARTERS_COUNTRY_CODE', right_on='RETAILER_COUNTRY_COUNTRY_CODE'
    ).drop(columns='RETAILER_HEADQUARTERS_COUNTRY_CODE')

result = pd.merge(
    result, sales_territory, left_on='RETAILER_COUNTRY_SALES_TERRITORY_CODE', right_on='SALES_TERRITORY_SALES_TERRITORY_CODE'
    ).drop(columns='RETAILER_COUNTRY_SALES_TERRITORY_CODE')

# SALES_DEMOGRAPHIC_DEMOGRAPHIC_CODE       object
# SALES_DEMOGRAPHIC_SALES_PERCENT          object
# RETAILER_HEADQUARTERS_RETAILER_CODEMR    object
# RETAILER_HEADQUARTERS_RETAILER_NAME      object
# RETAILER_HEADQUARTERS_ADDRESS1           object
# RETAILER_HEADQUARTERS_ADDRESS2           object
# RETAILER_HEADQUARTERS_CITY               object
# RETAILER_HEADQUARTERS_REGION             object
# RETAILER_HEADQUARTERS_POSTAL_ZONE        object
# RETAILER_HEADQUARTERS_PHONE              object
# RETAILER_HEADQUARTERS_FAX                object
# RETAILER_SEGMENT_SEGMENT_CODE            object
# RETAILER_SEGMENT_LANGUAGE                object
# RETAILER_SEGMENT_SEGMENT_NAME            object
# RETAILER_SEGMENT_SEGMENT_DESCRIPTION     object
# AGE_GROUP_AGE_GROUP_CODE                 object
# AGE_GROUP_UPPER_AGE                      object
# AGE_GROUP_LOWER_AGE                      object
# RETAILER_COUNTRY_COUNTRY_CODE            object
# RETAILER_COUNTRY_COUNTRY_EN              object
# RETAILER_COUNTRY_FLAG_IMAGE              object
# SALES_TERRITORY_SALES_TERRITORY_CODE     object
# SALES_TERRITORY_TERRITORY_NAME_EN        object


result['SALES_DEMOGRAPHIC_DEMOGRAPHIC_CODE'] = result['SALES_DEMOGRAPHIC_DEMOGRAPHIC_CODE'].astype('int')
result['SALES_DEMOGRAPHIC_SALES_PERCENT'] = result['SALES_DEMOGRAPHIC_SALES_PERCENT'].astype('float')
result['RETAILER_HEADQUARTERS_RETAILER_CODEMR'] = result['RETAILER_HEADQUARTERS_RETAILER_CODEMR'].astype('int')
result['RETAILER_HEADQUARTERS_RETAILER_NAME'] = result['RETAILER_HEADQUARTERS_RETAILER_NAME'].astype('string')
result['RETAILER_HEADQUARTERS_ADDRESS1'] = result['RETAILER_HEADQUARTERS_ADDRESS1'].astype('string')
result['RETAILER_HEADQUARTERS_ADDRESS2'] = result['RETAILER_HEADQUARTERS_ADDRESS2'].astype('string')
result['RETAILER_HEADQUARTERS_CITY'] = result['RETAILER_HEADQUARTERS_CITY'].astype('string')
result['RETAILER_HEADQUARTERS_REGION'] = result['RETAILER_HEADQUARTERS_REGION'].astype('string')
result['RETAILER_HEADQUARTERS_POSTAL_ZONE'] = result['RETAILER_HEADQUARTERS_POSTAL_ZONE'].astype('string')
result['RETAILER_HEADQUARTERS_PHONE'] = result['RETAILER_HEADQUARTERS_PHONE'].astype('string')
result['RETAILER_HEADQUARTERS_FAX'] = result['RETAILER_HEADQUARTERS_FAX'].astype('string')
result['RETAILER_SEGMENT_SEGMENT_CODE'] = result['RETAILER_SEGMENT_SEGMENT_CODE'].astype('int')
result['RETAILER_SEGMENT_LANGUAGE'] = result['RETAILER_SEGMENT_LANGUAGE'].astype('string')
result['RETAILER_SEGMENT_SEGMENT_NAME'] = result['RETAILER_SEGMENT_SEGMENT_NAME'].astype('string')
result['RETAILER_SEGMENT_SEGMENT_DESCRIPTION'] = result['RETAILER_SEGMENT_SEGMENT_DESCRIPTION'].astype('string')
result['AGE_GROUP_AGE_GROUP_CODE'] = result['AGE_GROUP_AGE_GROUP_CODE'].astype('int')
result['AGE_GROUP_UPPER_AGE'] = result['AGE_GROUP_UPPER_AGE'].astype('int')
result['AGE_GROUP_LOWER_AGE'] = result['AGE_GROUP_LOWER_AGE'].astype('int')
result['RETAILER_COUNTRY_COUNTRY_CODE'] = result['RETAILER_COUNTRY_COUNTRY_CODE'].astype('int')
result['RETAILER_COUNTRY_COUNTRY_EN'] = result['RETAILER_COUNTRY_COUNTRY_EN'].astype('string')
result['RETAILER_COUNTRY_FLAG_IMAGE'] = result['RETAILER_COUNTRY_FLAG_IMAGE'].astype('string')
result['SALES_TERRITORY_SALES_TERRITORY_CODE'] = result['SALES_TERRITORY_SALES_TERRITORY_CODE'].astype('int')
result['SALES_TERRITORY_TERRITORY_NAME_EN'] = result['SALES_TERRITORY_TERRITORY_NAME_EN'].astype('string')
